language: csharp

mono:
 - 4.4.1

os:
 - linux

env:
 - TRAVIS_OS_UNAME=$(uname -s)

solution: StreamCryptor.sln

install:
 - mono .nuget/nuget.exe restore StreamCryptor.sln
 - mono .nuget/nuget.exe install NUnit.Runners -Version 3.4.1 -OutputDirectory testrunner

before_script:
 - bash travis-build-libsodium.sh

script:
 - xbuild StreamCryptor.sln
 - mono ./testrunner/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe ./Tests/bin/Debug/Tests.dll