language: c

os:
 - osx
 - linux
 
env:
 global:
  - EnableNuGetPackageRestore=true 
  - TRAVIS_OS_UNAME=$(uname -s)
 matrix:
  - MONO_VERSION="3.8.0"

install:
 - if [[ $TRAVIS_OS_UNAME = 'Linux' ]]; then bash travis-linux-deps.sh; fi
 - if [[ $TRAVIS_OS_UNAME = 'Darwin' ]]; then bash travis-osx-deps.sh; fi
 
before_script:
 - bash travis-build-libsodium.sh
 
script:
 - xbuild StreamCryptor.sln
 - bash nunit-console.sh ./Tests/bin/Debug/Tests.dll