language: csharp

mono:
 - 4.4.1

os:
 - linux

env:
 - TRAVIS_OS_UNAME=$(uname -s)

solution: StreamCryptor.sln

install:
 - nuget restore StreamCryptor.sln
 - nuget install NUnit.Runners -Version 3.4.1 -OutputDirectory testrunner

before_script:
 - bash travis-build-libsodium.sh

script:
 - xbuild StreamCryptor.sln
 - mono ./testrunner/NUnit.Runners.3.4.1/tools/nunit-console.exe ./Tests/bin/Debug/Tests.dll