language: csharp

mono:
 - 4.4.1

os:
 - linux

env:
 - TRAVIS_OS_UNAME=$(uname -s)

solution: StreamCryptor.sln

install:
 - nuget restore StreamCryptor.sln

before_script:
 - bash travis-build-libsodium.sh

script:
 - xbuild StreamCryptor.sln
 - bash nunit-console.sh ./Tests/bin/Debug/Tests.dll