language: c

env:
 global:
  - EnableNuGetPackageRestore=true 
  - TRAVIS_OS_UNAME=$(uname -s)
 matrix:
  - MONO_VERSION="3.8.0"

os:
 - linux

install:
 - if [[ $TRAVIS_OS_UNAME = 'Linux' ]]; then bash travis-linux-deps.sh; fi

script:
 - xbuild StreamCryptor.sln
 - bash nunit-console.sh ./Tests/bin/Debug/Tests.dll