language: c

os:
 - osx
 - linux
 
env:
 - EnableNuGetPackageRestore=true 
 - TRAVIS_OS_UNAME=$(uname -s)

install:
 - if [[ $TRAVIS_OS_UNAME = 'Linux' ]]; then bash travis-linux-deps.sh; fi
 - if [[ $TRAVIS_OS_UNAME = 'Darwin' ]]; then bash travis-osx-deps.sh; fi
 
before_script:
 - bash travis-build-libsodium.sh
 
script:
 - xbuild StreamCryptor.sln
 - cp /home/travis/build/bitbeans/StreamCryptor/packages/libsodium-net.0.6.0-beta1/lib/Net40/Sodium.dll.config /home/travis/build/bitbeans/StreamCryptor/StreamCryptor/bin/Debug/Sodium.dll.config
 - bash nunit-console.sh ./Tests/bin/Debug/Tests.dll