language: objective-c

env:
 - TRAVIS_OS_UNAME=$(uname -s)
 global:
  - EnableNuGetPackageRestore=true 
 matrix:
  - MONO_VERSION="3.8.0"
os:
 - linux

install:
 - if [[ $TRAVIS_OS_UNAME = 'Linux' ]]; then bash travis-linux-deps.sh; fi

script:
 - xbuild StreamCryptor.sln
 - bash nunit-console.sh ./Tests/bin/Debug/Tests.dll